# Generated by Django 3.2.23 on 2025-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassrequest',
            name='request_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('emergency', 'Emergency')], default='normal', max_length=20),
        ),
    ]
